#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json
# See https://www.git-town.com/configuration-file for details
[branches]
main = "main"
order = "asc"
unknown-type = "feature"

[create]
new-branch-type = "feature"
share-new-branches = "no"
stash = true

[propose]
breadcrumb = "branches"
breadcrumb-direction = "down"

[ship]
delete-tracking-branch = false
ignore-uncommitted = false
strategy = "fast-forward"

[sync]
auto-sync = false
detached = false
feature-strategy = "rebase"
perennial-strategy = "ff-only"
prototype-strategy = "rebase"
push-branches = true
push-hook = true
tags = false
upstream = true
